all:
  vars:
    domain: test.ansible.no
    fileshare_mount_point: ""
    router_default_gw: 172.17.0.2

    dns_servers:
      - "{{ router_default_gw }}"
      - 8.8.8.8
      - 8.8.4.4

  children:
    router:
      children:
        virtual:
          hosts:
            kb0:

    router_clients:
      children:
        baremetal:
          children:
            cdh_utility:
              hosts:
                kb1:
            
            cdh_master:
              hosts:
                kb2:

            cdh_gateway:
              hosts:
                kb3:

            cdh_data:
              hosts:
                kb4:

        #virtual:
        #  hosts:
        #    kb2:
